name: py12
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel
  - pip:
      - pyaes==1.6.1
      - pyasn1==0.6.1
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - rsa==4.9.1
      - telethon==1.41.2
